version: "3.8"
services:
  server:
    build: ./server
    container_name: server_c
    ports:
      - '3000:3000'
    # volumes:
    #   - ./server:/app
    #   - ./app/node_modules
  client:
    build: ./client
    container_name: client_c
    ports:
      - "3001:3001"
    stdin_open: true
    tty: true